# to set up 'kube_node' nodes
- hosts: kube_node
  roles:
  # inventory_hostname 表示当前定义的hosts主机名
  - { role: kube-lb, when: "inventory_hostname not in groups['kube_master']" }
  - { role: kube-node, when: "inventory_hostname not in groups['kube_master']" }
